[package]
name = "mnist"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = { version = "2.1.1" }

[[bin]]
name = "mnist"
path = "main.rs"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
